# Generated by Django 3.2.16 on 2022-12-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapAct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cap_act', models.IntegerField()),
                ('ren_dt', models.DateTimeField()),
                ('act_bal', models.IntegerField()),
                ('wdr_pri', models.IntegerField(blank=True, null=True)),
                ('dps_pri', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cap_act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('key', models.IntegerField(db_column='Key', primary_key=True, serialize=False)),
                ('field', models.DateTimeField(db_column='Field')),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('diff', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModAct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mod_ren_dt', models.DateTimeField()),
                ('tot_mod_pri', models.IntegerField()),
                ('tot_mod_prf', models.IntegerField()),
                ('tot_mod_inv', models.IntegerField()),
                ('tot_mod_rtr', models.FloatField()),
                ('tot_mod_iem_cd', models.IntegerField()),
                ('tot_mod_mon_rtr', models.FloatField()),
                ('tot_mod_iem_rtr', models.FloatField()),
                ('tot_mod_iem_per_rtr', models.CharField(blank=True, max_length=100, null=True)),
                ('tot_mod_iem_qty', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mod_act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModInfo',
            fields=[
                ('mod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mod_act', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModSign',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ord_sig', models.IntegerField()),
                ('ord_sig_dt', models.DateTimeField()),
                ('iem_cd', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_sign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModTrs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ord_dt', models.DateTimeField()),
                ('iem_cd', models.IntegerField()),
                ('sby_dit_cd', models.IntegerField()),
                ('cns_qty', models.IntegerField()),
                ('orr_pr', models.IntegerField()),
            ],
            options={
                'db_table': 'mod_trs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RtDiv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usr_rtr', models.FloatField()),
                ('ren_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'rt_div',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrsCheck',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('btn_clk_cd', models.IntegerField()),
                ('btn_clk_dt', models.DateTimeField()),
                ('usr_ord_cd', models.IntegerField()),
                ('usr_ord_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'trs_check',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsrInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pas_wd', models.CharField(max_length=32)),
                ('cus_nam', models.TextField()),
                ('mypg_cd', models.IntegerField()),
                ('cus_id', models.CharField(max_length=32)),
                ('usr_act', models.IntegerField()),
            ],
            options={
                'db_table': 'usr_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsrOrdInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ord_cd', models.IntegerField()),
                ('ord_amt', models.IntegerField()),
                ('ord_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'usr_ord_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsrPrfInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ren_dt', models.DateTimeField()),
                ('tot_cus_rtr', models.FloatField()),
            ],
            options={
                'db_table': 'usr_prf_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsrTrnInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ren_dt', models.DateTimeField()),
                ('tot_cus_pri', models.IntegerField()),
                ('tot_cus_prf', models.IntegerField()),
                ('tot_cus_inv', models.IntegerField()),
                ('tot_cus_rtr', models.FloatField()),
            ],
            options={
                'db_table': 'usr_trn_info',
                'managed': False,
            },
        ),
    ]
