# Generated by Django 3.2.16 on 2023-01-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accountemailaddress_accountemailconfirmation_accountsuser_accountsusergroups_accountsuseruserpermiss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsrInfo',
        ),
    ]
