# Generated by Django 3.2.16 on 2023-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_usrinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModPrfInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ren_dt', models.DateTimeField()),
                ('tot_mod_rtr', models.FloatField()),
            ],
            options={
                'db_table': 'mod_prf_info',
                'managed': False,
            },
        ),
    ]
