# Generated by Django 3.2.16 on 2023-01-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_modprfinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsrOrdInfo',
        ),
    ]
