# Generated by Django 3.2.16 on 2023-01-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_usrordinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exchage_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'interest_rate',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RtDiv',
        ),
    ]
