# Generated by Django 3.2.16 on 2023-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
